{
	"_Type": "Action.Type.ODataService.UpdateEntity",
	"Target": {
		"EntitySet": "Order_Details_Extendeds",
		"Service": "/prueba/Services/prueba.service",
		"ReadLink": "{@odata.readLink}"
	},
	"Properties":  {
	"OrderID": "#Control:OrderID/#Value",
	"ProductID": "#Control:ProductID/#Value",
	"ProductName": "#Control:ProductName/#Value",
	"UnitPrice": "#Control:UnitPrice/#Value",
	"Quantity": "#Control:Quantity/#Value",
	"Discount": "#Control:Discount/#Value",
	"ExtendedPrice": "#Control:ExtendedPrice/#Value"
},
	"UpdateLinks": [],
	"ActionResult": {
		"_Name": "update"
	},
	"OnSuccess": "/prueba/Actions/UpdateEntitySuccessMessage.action",
	"OnFailure": "/prueba/Actions/UpdateEntityFailureMessage.action"
}