{
	"CreateLinks": [],
	"OnFailure": "/prueba/Actions/CreateEntityFailureMessage.action",
	"OnSuccess": "/prueba/Actions/CreateEntitySuccessMessage.action",
	"Properties": {
	"OrderID": "#Control:OrderID/#Value",
	"ProductID": "#Control:ProductID/#Value",
	"UnitPrice": "#Control:UnitPrice/#Value",
	"Quantity": "#Control:Quantity/#Value",
	"Discount": "#Control:Discount/#Value"
},
	"Target": {
		"EntitySet": "Order_Details",
		"Service": "/prueba/Services/prueba.service"
	},
	"ActionResult": {
		"_Name": "create"
	},
	"_Type": "Action.Type.ODataService.CreateEntity"
}