{
	"_Type": "Action.Type.ODataService.UpdateEntity",
	"Target": {
		"EntitySet": "CustomerDemographics",
		"Service": "/prueba/Services/prueba.service",
		"ReadLink": "{@odata.readLink}"
	},
	"Properties":  {
	"CustomerTypeID": "#Control:CustomerTypeID/#Value",
	"CustomerDesc": "#Control:CustomerDesc/#Value"
},
	"UpdateLinks": [],
	"ActionResult": {
		"_Name": "update"
	},
	"OnSuccess": "/prueba/Actions/UpdateEntitySuccessMessage.action",
	"OnFailure": "/prueba/Actions/UpdateEntityFailureMessage.action"
}